### ISSUE TITLE
Dense matrix input should support variables in rows.

### ISSUE THREAD

**Issue by kuol** [alteryx/AlteryxPrescriptive#21]
I'm trying to create an optimization example with fantasy baseball daily lineup and have just realized that  how useful this input format will be! I personally think it may be more useful than the slam matrix input format for people who want to do everything within Alteryx. I can explain more once I get the example workflow done. 

So here's the old format,

x      | y     | z
------|------|----
1   | 2   |  3 
1   |1    |  0
Here's the equivalent new format I'm thinking of:

variable |    c1  |     c2
-----------|--------|--------
x         |      1     |    1
y         |      2      |   1
z         |      3      |   0

**Comment by ramnathv** [comment]
This should be fairly straightforward to support. I have been thinking that we should extend the A matrix to a data frame where users can specify the name of the constraint. Given this, we can easily identify between the two formats. So, the two inputs would be

__Constraints in Rows__

|constraint |  x|  y|  z|
|:----------|--:|--:|--:|
|c1         |  1|  2|  3|
|c2         |  1|  1|  0|


__Variables in Rows__

variable |    c1  |     c2
-----------|--------|--------
x         |      1     |    1
y         |      2      |   1
z         |      3      |   0

**Comment by kuol** [comment]
The benefit of __Variables in Rows__ format  is that: if there are many decision variables, it won't cause a problem.

**Comment by ramnathv** [comment]
Yeah. But we need to support both because there would be situations where there are more constraints. If we enforce that A matrix have the variables names specified in O as columns or rows, we can infer the type of matrix based on the field names. However, it is always better to be explicit, where the cost of being so is not high, which is the case here I think.

**Comment by kuol** [comment]
I agree.

**Comment by ramnathv** [comment]
While, we are on this, I think we should also let the user specify a description of the constraint (optionally). This will allow more custom reporting that will be meaningful to the decision maker.

|constraint |description |  x|  y|  z|
|:----------|:-----------|--:|--:|--:|
|c1         |Capacity    |  1|  2|  3|
|c2         |Demand      |  1|  1|  0|

In the variables in rows case, this would be an optional row named `description`. We can make it explicit that the user cannot have a decision variable named `description`. Note that for the `slam` matrix case, the user can specify the `constraint` and `description` in the `B` matrix.

We want to be careful how we document this, since by providing so much flexibility to the user, we are also running the risk of users making errors.

**Comment by kuol** [comment]
Yeah, I feel it's time for a **PM** + **beta user** to chime in :-)

**Comment by kuol** [comment]
Yeah, I feel it's time for a **PM + beta user** to chime in :-)

**Comment by ramnathv** [comment]
This opens up another related issue. Currently, we are assuming that the A matrix has the variables in the same order as in the O matrix. In other words, we make no attempt to match up the column names of the A matrix with the `variable` column in the `O` matrix. This could lead to subtle bugs, where the user orders things differently.

I believe in a macro failing early, with a clear error message. So, while it might be imposing on the user to ensure that column names in A have to match up with variable names in O, it will help us avoid subtle bugs, while at the same time allowing us to provide more clear cut error messages. In this case the error message would be:

> The variable names in `O` must match up agains the column names in `A` (or the `variable` column should the matrix be ordered by variable.

**Comment by ramnathv** [comment]
This issue is getting too big. Let us talk tomorrow and split it up into smaller issues. These enhancements are fairly easy to implement. The main issue is agreeing on what the spec is going to be. But I think we can resolve that with some conversation.

**Comment by kuol** [comment]
Yeah, __Variable in Rows__ is kind of important for my example. Others are also very important, but maybe we can stage them in the __Code Hardening__ stage? -- If we don't have time for this. The nice thing is we have already documented them here :)

**Comment by ramnathv** [comment]
This is complete. I will create a new issue for proactive error handling.
